export default {
  category: [
    {
      id: '1',
      category: 'Milk ',
    },
    {
      id: '2',
      category: 'Juice',
    },
    {
      id: '3',
      category: 'Tea ',
    },
    {
      id: '4',
      category: 'Coffee',
    },
  ],
  product: [
    {
      id: '1',
      categoryId: '1',
      name: 'Date Milkshake',
      rating: '3.8',
      price: '3',
      images: require('./UsPics/a1.png'),
      added: 0,
    },
    {
      id: '2',
      categoryId: '1',
      name: 'Chocolate Malt Milkshake',
      rating: '4.5',
      price: '2.88',
      images: require('./UsPics/a2.png'),
      added: 0,
    },
    {
      id: '3',
      categoryId: '1',
      name: 'Almond Saffron Milkshake',
      rating: '3.9',
      price: '3.5',
      images: require('./UsPics/a3.png'),
      added: 0,
    },
    {
      id: '4',
      categoryId: '1',
      name: 'Musk Melon Milkshake',
      rating: '3.5',
      price: '4',
      images: require('./UsPics/a4.png'),
      added: 0,
    },
    {
      id: '5',
      categoryId: '1',
      name: 'Banana Milkshake',
      rating: '4',
      price: '4.5',
      images: require('./UsPics/a5.png'),
      added: 0,
    },
    {
      id: '6',
      categoryId: '1',
      name: 'Beetroot Milkshake',
      rating: '3.4',
      price: '5',
      images: require('./UsPics/a6.png'),
      added: 0,
    },
    {
      id: '7',
      categoryId: '1',
      name: 'Chocolate Hazelnut Milkshake',
      rating: '3.6',
      price: '3.5',
      images: require('./UsPics/a7.png'),
      added: 0,
    },
    {
      id: '8',
      categoryId: '2',
      name: 'Apple',
      rating: '3.8',
      price: '2.99',
      images: require('./UsPics/b1.png'),
      added: 0,
    },
    {
      id: '9',
      categoryId: '2',
      name: 'Kiwi Juice',
      rating: '4.1',
      price: '4',
      images: require('./UsPics/b2.png'),
      added: 0,
    },
    {
      id: '10',
      categoryId: '2',
      name: 'Cranberry',
      rating: '3.9',
      price: '15',
      images: require('./UsPics/b3.png'),
      added: 0,
    },
    {
      id: '11',
      categoryId: '2',
      name: 'Prune',
      rating: '3.3',
      price: '18',
      images: require('./UsPics/b4.png'),
      added: 0,
    },
    {
      id: '12',
      categoryId: '2',
      name: 'Orange',
      rating: '4.2',
      price: '2',
      images: require('./UsPics/b5.png'),
      added: 0,
    },
    {
      id: '13',
      categoryId: '2',
      name: 'Acai berry',
      rating: '3.6',
      price: '3',
      images: require('./UsPics/b6.png'),
      added: 0,
    },
    {
      id: '14',
      categoryId: '3',
      name: 'Black Tea',
      rating: '3.7',
      price: '5',
      images: require('./UsPics/c1.png'),
      added: 0,
    },
    {
      id: '15',
      categoryId: '3',
      name: 'Earl Grey',
      rating: '3.2',
      price: '4.99',
      images: require('./UsPics/c2.png'),
      added: 0,
    },
    {
      id: '16',
      categoryId: '3',
      name: 'Green Tea',
      rating: '4.8',
      price: '3.5',
      images: require('./UsPics/c3.png'),
      added: 0,
    },
    {
      id: '17',
      categoryId: '3',
      name: 'Oolong Tea',
      rating: '3.2',
      price: '6',
      images: require('./UsPics/c4.png'),
      added: 0,
    },
    {
      id: '18',
      categoryId: '4',
      name: 'Doppio',
      rating: '3.4',
      price: '4.99',
      images: require('./UsPics/d1.png'),
      added: 0,
    },
    {
      id: '19',
      categoryId: '4',
      name: 'Cortado',
      rating: '3.8',
      price: '3',
      images: require('./UsPics/d2.png'),
      added: 0,
    },
    {
      id: '20',
      categoryId: '4',
      name: 'Red Eye',
      rating: '3.5',
      price: '2.88',
      images: require('./UsPics/d3.png'),
      added: 0,
    },
    {
      id: '21',
      categoryId: '4',
      name: 'Galão',
      rating: '3.8',
      price: '3.5',
      images: require('./UsPics/d4.png'),
      added: 0,
    },
    {
      id: '22',
      categoryId: '4',
      name: 'Lungo',
      rating: '3.5',
      price: '4',
      images: require('./UsPics/d5.png'),
      added: 0,
    },
    {
      id: '23',
      categoryId: '4',
      name: 'Macchiato',
      rating: '4',
      price: '4.5',
      images: require('./UsPics/d6.png'),
      added: 0,
    },
  ],
  details: [
    {
      productid: '1',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '1',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '1',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '1',
      'sugar level': '100%',
    },
    {
      productid: '2',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '2',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '2',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '2',
      'sugar level': '100%',
    },
    {
      productid: '3',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '3',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '3',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '3',
      'sugar level': '100%',
    },
    {
      productid: '4',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '4',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '4',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '4',
      'sugar level': '100%',
    },
    {
      productid: '5',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '5',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '5',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '5',
      'sugar level': '100%',
    },
    {
      productid: '6',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '6',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '6',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '6',
      'sugar level': '100%',
    },
    {
      productid: '7',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '7',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '7',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '7',
      'sugar level': '100%',
    },
    {
      productid: '8',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '8',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '8',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '8',
      'sugar level': '100%',
    },
    {
      productid: '9',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '9',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '9',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '9',
      'sugar level': '100%',
    },
    {
      productid: '10',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '10',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '10',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '10',
      'sugar level': '100%',
    },
    {
      productid: '11',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '11',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '11',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '11',
      'sugar level': '100%',
    },
    {
      productid: '12',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '12',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '12',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '12',
      'sugar level': '100%',
    },
    {
      productid: '13',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '13',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '13',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '13',
      'sugar level': '100%',
    },
    {
      productid: '14',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '14',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '14',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '14',
      'sugar level': '100%',
    },
    {
      productid: '15',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '15',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '15',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '15',
      'sugar level': '100%',
    },
    {
      productid: '16',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '16',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '16',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '16',
      'sugar level': '100%',
    },
    {
      productid: '17',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '17',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '17',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '17',
      'sugar level': '100%',
    },
    {
      productid: '18',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '18',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '18',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '18',
      'sugar level': '100%',
    },
    {
      productid: '19',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '19',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '19',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '19',
      'sugar level': '100%',
    },
    {
      productid: '20',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '20',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '20',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '20',
      'sugar level': '100%',
    },
    {
      productid: '21',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '21',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '21',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '21',
      'sugar level': '100%',
    },
    {
      productid: '22',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '22',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '22',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '22',
      'sugar level': '100%',
    },
    {
      productid: '23',
      'sugar level': '0%',
      'choice size': 'small=125ml',
    },
    {
      productid: '23',
      'sugar level': '25%',
      'choice size': 'medium=175ml',
    },
    {
      productid: '23',
      'sugar level': '50%',
      'choice size': 'large=250ml',
    },
    {
      productid: '23',
      'sugar level': '100%',
    },
  ],
};
